In [1]:
import numpy as np
import tensorflow as tf
import cv2
LSTM_SIZE = 4
CROP_SIZE = 2

In [27]:
imagePlaceholder = tf.placeholder(tf.uint8, shape=(None, CROP_SIZE, CROP_SIZE, 3))
prevLstmState = tuple([tf.placeholder(tf.float32, shape=(None, LSTM_SIZE)) for _ in range(4)])
batch_size = tf.placeholder(tf.int32, shape=())
tracked_data = {}

In [21]:
a = [np.zeros((1, 4)) for _ in range(4)]
len(a)

4

In [45]:
lstmState = [np.zeros((1, LSTM_SIZE)) for _ in range(4)] # [X, X, X, X]
#pastBBox = np.array(starting_box)
croppedInput0 = croppedInput1 = np.zeros((2,4,3), np.uint8)
print(croppedInput0.shape)
img = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]])
print(img.shape)

(2, 4, 3)
(2, 4, 3)


In [47]:
feed_dict = {
            #imagePlaceholder : [croppedInput0],
            #prevLstmState : lstmState,
            #batch_size : 1,
            }
feed_dict

{}

In [53]:
img

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [77]:
img[np.newaxis].shape
img

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [76]:
img[:,:,::-1]

array([[[ 3,  2,  1],
        [ 6,  5,  4],
        [ 9,  8,  7],
        [12, 11, 10]],

       [[15, 14, 13],
        [18, 17, 16],
        [21, 20, 19],
        [24, 23, 22]]])

In [73]:
np.tile(img[np.newaxis,...], (2,1,1,1))

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]]])

In [87]:
dic = {}
dic[0]=3
dic

{0: 3}